version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: cypress
    versions:
    - 7.0.0
    - 7.0.1
  - dependency-name: rollup
    versions:
    - 2.38.2
    - 2.38.4
- package-ecosystem: npm
  directory: "/examples/articles"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/blocks"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/examples/masonry"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 2
