name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  cypress:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ 14 ]
        browser: [ firefox, chrome ]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          browser: ${{ matrix.browser }}
          headless: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
